const List<String> providerType = [
  'Resturant',
  'Shop',
];

const List<String> segmentsResturants = [
  'Regular Resturant',
  'Home Based Kitchen',
];
const List<String> cuisineList = [
  "Cuisine",
  'American',
  'Asian',
  'Brazilian',
  'Burgers',
  'Cakes & Bakery',
  'Chinese',
  'Desserts',
  'European',
  'Fast Food',
  'Filipino',
  'French',
  'German',
  'Greek',
  'Halal',
  'Healthy Food',
  'Indian',
  'Indonesian',
  'International',
  'Italian',
  'Japanese',
  'Korean',
  'Lebanese',
  'Malaysian',
  'Mediterranean',
  'Maxican',
  'Middle Eastern',
  'Pakistani',
  'Pizza',
  'Sandwiches',
  'Seafood',
  'Singaporean',
  'Spanish',
  'Thai',
  'Turkish',
  'Vegetarian',
  'Vitnamese',
  'Westren',
];
